on: push
jobs:
  windows_unit_test:
    name: Windows Unit Test
    runs-on: windows-latest
    env:
      GO_VERSION: 1.13.4
      GO111MODULE: "off"
      GOROOT: 
    steps:
    - name: Clone Repo
      run: |
        New-Item -ItemType Directory -Force -Path .\src\k8s.io
        cd ./src/k8s.io/
        git clone -c core.symlinks=true https://github.com/kubernetes/kubernetes.git
    - name: Install Go
      run: |
        choco install golang --version $env:GO_VERSION -y -vv
        #Invoke-Webrequest ("https://dl.google.com/go/go" + $env:GO_VERSION + ".windows-amd64.msi") -Outfile go.msi
        #msiexec.exe /qn /i ./go.msi
        [Environment]::SetEnvironmentVariable("PATH", ("C:\Go\bin;" + $env:PATH), "Machine")
        refreshenv
        go version
    #- uses: actions/checkout@v2-beta
    #  name: Clone Repo
    #  with:
    #    path: ./src/k8s.io/kubernetes
    - name: Install gotestsum
      #env:
      #  GOPATH: ${{ runner.workspace }}
      run: |
        $env:GOPATH = (Get-Location)
        cd ./src/k8s.io/kubernetes
        go build -o C:\Go\bin\gotestsum ./vendor/gotest.tools/gotestsum
    - name: Unit Test
      #env:
      #  GOPATH: ${{ runner.workspace }}
      run: |
        $env:GOPATH = (Get-Location)
        cd ./src/k8s.io/kubernetes
        C:\Go\bin\gotestsum -- ./pkg/... ./cmd/...
        go test ./pkg/... ./cmd/...

