on: push
jobs:
  windows_unit_test:
    name: Windows Unit Test
    runs-on: windows-latest
    env:
      GO111MODULE: "off"
    steps:
    # Windows doesn't have symlinks on by default.
    # We need these for staging to work.
    # This must be enabled BEFORE cloning.
    # TLDR historically symlinks were admin-only on windows, 
    - name: Enable git Symlinks
      run: |
        git config --global core.symlinks true
    # actually checkout the repo, GitHub actions does not by default
    - uses: actions/checkout@v2-beta
      name: Clone Repo
      with:
        path: ./src/k8s.io/kubernetes
    # GitHub actions ship with some arbitrary Go version
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.4
    # Debug go version for sanity
    - name: Verify Go
      run: |
        go version
    # install gotestsum so we can get nice output
    - name: Build gotestsum
      run: |
        $env:GOPATH = (Get-Location)
        cd ./src/k8s.io/kubernetes
        go build -o ./_output/gotestsum ./vendor/gotest.tools/gotestsum
    # actually run unit tests
    - name: Unit Test
      run: |
        $env:GOPATH = (Get-Location)
        cd ./src/k8s.io/kubernetes
        ./_output/gotestsum --help
        ./_output/gotestsum -- ./pkg/... ./cmd/...

