on: push
jobs:
  windows_unit_test:
    name: Windows Unit Test
    runs-on: windows-latest
    env:
      GO_VERSION: 1.13.4
      GO111MODULE: "off"
      GOROOT: 
    steps:
    - name: Install Go
      run: |
        choco install golang --version $env:GO_VERSION -y -vv
        [Environment]::SetEnvironmentVariable("PATH", ($env:PATH + ";C:\Go\bin"), "Machine")
        go version
    - uses: actions/checkout@v2-beta
      name: Clone Repo
      with:
        path: ./src/k8s.io/kubernetes
    - name: Install gotestsum
      #env:
      #  GOPATH: ${{ runner.workspace }}
      run: |
        $env:GOPATH = (Get-Location)
        cd ./src/k8s.io/kubernetes
        go build -o C:\Go\bin\gotestsum ./vendor/gotest.tools/gotestsum
    - name: Unit Test
      #env:
      #  GOPATH: ${{ runner.workspace }}
      run: |
        $env:GOPATH = (Get-Location)
        cd ./src/k8s.io/kubernetes
        gotestsum ./pkg/... ./cmd/...

